spring:
  application:
    name: yap-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/yap-database
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate

security:
  jwt:
    expiration-time: 86400000
    secret-key: ${JWT_SECRET:tiL5CUsiNAa1qkRZ4pt1x5f8gnp3aAp0tiL5CUsiNAa1qkRZ4pt1x5f8gnp3aAp0}

notification:
    enabled: true
    public-key: ${VAPID_PUBLIC_KEY:public-key}
    private-key: ${VAPID_PRIVATE_KEY:private-key}
